services:
  - type: web
    name: smart-goalie-app
    env: python
    plan: free
    buildCommand: pip install -r src/requirements.txt
    startCommand: streamlit run src/streamlit_app.py --server.port $PORT

  - type: web
    name: mistral-llm-backend
    env: python
    plan: starter
    buildCommand: pip install -r llm_backend/requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    rootDir: llm_backend