services:
  - type: web
    name: smart-goalie-app
    env: python
    plan: free
    buildCommand: pip install -r src/requirements.txt
    startCommand: streamlit run src/streamlit_app.py --server.port $PORT
    rootDir: src

  - type: web
    name: goal-status-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    rootDir: .
